# Configuration file for MegaLinter
---

# The listed linters will be run, but if errors are found, they will be considered as non blocking
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_SECRETLINT
  - SPELL_CSPELL

FILTER_REGEX_EXCLUDE: ''

APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
PRINT_ALL_FILES: true

# Linter configs
SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (\.gitignore|\.editorconfig)
